### ISSUE TITLE
年代別陽性患者数を表示する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#10]
[兵庫県](https://stop-covid19-hyogo.org/)がやっていた

わかりやすかったので真似したい

![Screen Shot 2020-03-22 at 13 00 04](https://user-images.githubusercontent.com/24912801/77241978-1509f380-6c3d-11ea-8bce-34e538651c27.png)

**Comment by shmokmt** [comment]
良さそう

**Comment by shmokmt** [comment]
時間取れそうなので、こちら着手しますね :)
