### ISSUE TITLE
円グラフのグラデーションを見やすくしたい

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#104]
### 「見づらい」という意見があった

特に老眼の人

色が近すぎることが問題だと思う
最後の色がもっと薄くなっていいから，もう少し色を離したい

### タップすると色が全く同じになる

グラフをタップしてツールチップを表示させると，若干色が暗くなるのだけど，そのせいで隣の属性と全く同じ色になってしまっている
これも色を離したら解決すると思う

タップ前
![スクリーンショット 2020-03-29 19 36 02](https://user-images.githubusercontent.com/24912801/77846963-8b39c780-71f4-11ea-9c75-fef1076c7bf8.png)

タップ後 (60s-70sと80s-90sが同じ色になっている)
![IMG_0188](https://user-images.githubusercontent.com/24912801/77846868-0484ea80-71f4-11ea-8a20-57a94afced87.jpg)

**Comment by varu3** [comment]
本家の方でもチャートの色を配慮する議論がされていましたね。

参考
https://github.com/tokyo-metropolitan-gov/covid19/issues/1172
