### ISSUE TITLE
職業別陽性患者数の必要性

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#105]
医療関係者が多いかどうか，みたいな情報があったらいいのかなとふと思いました
情報はあるので，実装可能です

ないならないでいいと思っているのですが，どうでしょうか

**Comment by shmokmt** [comment]
こちらもまだ必要ない気がしていますが、みなさんいかがでしょうか

**Comment by nojiri1098** [comment]
現時点では必要ないということで，一旦閉じます
