### ISSUE TITLE
退院済みの患者数 (感染中の患者数) を表示する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#111]
現段階で公開されている情報で
「誰が退院したか」はわからないですが，
「何人退院したか」はわかります

感染中の人数を知りたいというニーズがあるので対応したい
https://github.com/covid19-oita/covid19/issues/61#issuecomment-603650116

どのように表示するかは要検討

**Comment by satetsu** [comment]
> 現段階で公開されている情報で
> 「誰が退院したか」はわからないですが，
> 「何人退院したか」はわかります

大分県の方針で、「誰が退院したか」は公表されません。
したがいまして、『[440001_oita_covid19_patients.csv](https://github.com/covid19-oita/covid19/blob/development/static/data/440001_oita_covid19_patients.csv)』の［退院済フラグ］を使わない運用が必要です。

運用案については #61 に続きます。

**Comment by nojiri1098** [comment]
#121 に引き継ぎ
