### ISSUE TITLE
branch protection をかける

### ISSUE THREAD

**Issue by shmokmt** [covid19-oita/covid19#12]
他のコントリビュータが参加した場合にミスが起きないようにブランチを保護するように設定する。

例・masterとdevelopにpushできる人を制限する。

**Comment by nojiri1098** [comment]
@shmokmt 
これで設定したつもり
追加したいやつ，おかしいやつとかあったら教えて

### [master](https://github.com/covid19-oita/covid19/settings/branch_protection_rules/15181486)
- `deploy` チェック必須 (管理者含む)
- 管理者以外の push 禁止
- 管理者以外の delete 禁止

### [development](https://github.com/covid19-oita/covid19/settings/branch_protection_rules/15181490)
- 最新の development から分岐しないと merge できない (管理者含む)
- eslist と stylelint のチェック必須 (管理者含む)
- 管理者以外の push 禁止
- 管理者以外の delete 禁止

**Comment by shmokmt** [comment]
@nojiri1098 
ありがとうございます！
良いと思います！
