### ISSUE TITLE
データの出典を表示する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#128]
#121 を実装するにあたり「オープンデータを入手」を消してしまった

再度表示するとともに，URLを更新する
https://data.bodik.jp/dataset/_covid19

**Comment by varu3** [comment]
関連して、「当サイトについて」に
当サイトのグラフは「大分県オープンデータカタログサイト」にある新型コロナウイルス関連のデータを元に生成されている、という内容を明示するように修正した方が良いかと思います。
