### ISSUE TITLE
「感染が疑われるときは」を東京都のように作る

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#140]
今は大分県が発行するPDFに飛ばしていますが，[東京都](https://stopcovid19.metro.tokyo.lg.jp/flow)のように表示したほうがわかりやすい

[愛知県](https://stopcovid19.code4.nagoya/flow/)や[神奈川県](https://www.pref.kanagawa.jp/osirase/1369/flow)が東京都のページを改変して自県版を作っていたので，それを参考にすればできるはず．

表示する情報は「[県民の皆様へ](https://www.pref.oita.jp/uploaded/attachment/2072440.pdf)」などの公式情報を参考にしてください

**Comment by shmokmt** [comment]
メモ：今週中を目安に実装するペースで取り組む

**Comment by shmokmt** [comment]
@nojiri1098 と話した結果、県の方と協力して進める必要があると判断し、一旦ステイしています。

**Comment by nojiri1098** [comment]
もう作らないと思うのでcloseします
