### ISSUE TITLE
期間指定できるようにする

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#144]
この先数ヶ月経つと，必要以上に長期間のデータが表示されることになり，グラフが見づらくなる可能性があります

そこで，北海道のように表示するデータの期間を指定できるようにしたいです (@shmokmt の提案)

![c14b1f6741450e16a14409d213198381](https://user-images.githubusercontent.com/24912801/78472056-ee85a580-7770-11ea-9d8c-9d992273ceb8.gif)

**Comment by shmokmt** [comment]
リポジトリ: https://github.com/codeforsapporo/covid19

**Comment by shmokmt** [comment]
該当コンポーネントはこちら: https://github.com/codeforsapporo/covid19/blob/development/components/DateSelectSlider.vue

**Comment by shmokmt** [comment]
こちら自分持ちます。

**Comment by nojiri1098** [comment]
スライダーを実装してもTOSで期間指定がしにくいことがわかったので，横スクロールで実装することにした
ref. #216
