### ISSUE TITLE
タイ語の更新

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#184]
@PNNutkung
表現が変わったり，新しく追加されたりしたので，また翻訳をお願いしたいです

top page
![image](https://user-images.githubusercontent.com/24912801/79528555-3f689880-80a5-11ea-984e-aed420d7a129.png)

about page
![image](https://user-images.githubusercontent.com/24912801/79528628-76d74500-80a5-11ea-9f11-f6deb2c395d5.png)

**Comment by PNNutkung** [comment]
OK I will update Thai translation.
