### ISSUE TITLE
ページが正しく表示されることを確認するしくみを作りたい

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#193]
開発時には `/` しか表示しないので，他のページで正しくデータが表示されていないのにリリースしてしまうことがある．

たとえばv2.5.1では， カードの単体ページ `/cards/*` でデータが表示されないことに気づかないままリリースしてしまった．すべてのページを表示してみればすぐわかることだったが，人力ではそこまで気が回らないし，確認するのが面倒．

これからも同じことが起こる可能性があるので，すべてのページが正しく表示されていることを何らかの方法で確認できるようにしたい．たとえば，ページのスクショをとってPRのコメントに貼るなど (@shmokmt のアイデア)．

言語によって表示できなくなる場合がある (#230) ので，すべての言語でもチェックできるようにしたい．

意見や他のアイデアがあれば教えてください🙇

**Comment by shmokmt** [comment]
@NakaokaRei よかったらこのissueに取り組んでみませんか？ 👀

**Comment by NakaokaRei** [comment]
今いろいろ他にやることがあってできるかわからない。
結構急ぎやったりする？？

これは、新しいバージョンがリリースされたら自動でスクショ撮って、うまく表示されてなかったら自動でissueを書くみたいな仕組みを作るってこと？

**Comment by shmokmt** [comment]
@NakaokaRei

> 結構急ぎやったりする？？

全然急ぎではない。来月中とかでも良いよ。自分のペースで取り組んでくれれば大丈夫。

>  新しいバージョンがリリースされたら自動でスクショ撮って、うまく表示されてなかったら自動でissueを書くみたいな仕組みを作るってこと？

新しいバージョンがリリースする前にスクリーンショットを取りたいです。
バグを含んだままリリースするのを防ごうとしています。
issueを書くところまではやらなくて大丈夫です！

1.  GitHub Actions で master ブランチに向けてプルリクエストが作られるのをトリガーにして、各自ページのスクリーンショットを取るスクリプトを走らせる。
2. その各種ページのスクリーンショットをPRのコメントに貼り付ける。

みたいな感じです。スクリプトの言語はなんでも大丈夫です。
れいれいだと、PythonでChromiumをHeadlessにして走らせるコードを書くのがやりやすいと思います。

**Comment by NakaokaRei** [comment]
なるほど、とりあえず暇できたらまたコメントする。
Chromium、Headlessとか初耳やったんやけど、実装自体はそんなに難しくないぽいかな？

**Comment by shmokmt** [comment]
@NakaokaRei  https://github.com/swinton/screenshot-website
これ使ったらすぐ解決できそうなので、自分がやってしまいますね。 🙏
