### ISSUE TITLE
fix notation of language selector for Thai

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#195]
I think `ภาษาไทย` is better than `Thai`.

![image](https://user-images.githubusercontent.com/24912801/79721339-2538ef80-831d-11ea-82c1-6ee7a4a5d421.png)

**Comment by nojiri1098** [comment]
@PNNutkung
what do you think about it?

**Comment by PNNutkung** [comment]
> I think `ภาษาไทย` is better than `Thai`.
> 
> ![image](https://user-images.githubusercontent.com/24912801/79721339-2538ef80-831d-11ea-82c1-6ee7a4a5d421.png)
> 

I think `ภาษาไทย` is better. Thank you for adding. 😄

**Comment by nojiri1098** [comment]
OK, I will update it 👍
