### ISSUE TITLE
Error has occurred only in Indonesian

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#230]
we faced with the issue in https://github.com/covid19-oita/covid19/pull/229.
Please check out #229 and add a commit there if you contribute to this.

## The Problem
error has occurred only in Indonesian.

<img width="1440" alt="スクリーンショット 2020-05-10 23 01 50" src="https://user-images.githubusercontent.com/24912801/81501281-88adb000-9312-11ea-9f0d-b601ec4e1d71.png">

## Steps to Reproduce
change language to Indonesian.

**Comment by jiprastyo** [comment]
I have no expertise in website coding. 
But is it possible that the issue is caused by the translation file?
For example, a certain part of English part was translated way too long, longer than the allowed string length in that certain line?

**Comment by nojiri1098** [comment]
It's unlikely. I tried to shorten the longest line as same as that of English, but the error has occurred too...

**Comment by nojiri1098** [comment]
resolved in #229
