### ISSUE TITLE
円グラフの使用をやめる

### ISSUE THREAD

**Issue by shmokmt** [covid19-oita/covid19#231]
## 改善詳細 / Details of Improvement
- 性別年代を円グラフ表示しているが、円グラフではなく棒グラフ（横）にする。
理由として、人間は角度を目視で正確に捉えることができないので、数量の比較がしにくい等があげられます。

## 参考リンク
- https://dataviz.hatenablog.com/entry/2019/02/05/180316
- https://github.com/ft-interactive/chart-doctor/blob/master/visual-vocabulary/Visual-vocabulary-JP.pdf
- https://jikitourai.net/dont-use-piechart

**Comment by nojiri1098** [comment]
完成イメージ ([chart-doctor](ft-interactive/chart-doctor:visual-vocabulary/Visual-vocabulary-JP.pdf@master)より)
![image](https://user-images.githubusercontent.com/24912801/81766733-a4cb7000-9511-11ea-8632-6d0ceb5632ef.png)
