### ISSUE TITLE
英語対応

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#24]
英語版も大分県版にする

多言語対応選択メニューを復活させる (日本語と英語のみ)

**Comment by shmokmt** [comment]
@nojiri1098 README.md の英語版もメンテナンスしていく？　どうしよっか
https://github.com/covid19-oita/covid19/blob/development/docs/en/README.md

**Comment by nojiri1098** [comment]
せっかくだからそこまでやりたいね

**Comment by shmokmt** [comment]
![image](https://user-images.githubusercontent.com/32533860/77308789-d9575280-6d3e-11ea-8795-4c7abaa29e63.png)

メモ：SideNavigationの現状のi18nの適用状況
