### ISSUE TITLE
Update Indonesian translation

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#247]
There was a request from Oita pref. to publish support statuses in Oita pref. on our site, so we added a page  [/id/support](https://dev-covid19-oita.netlify.app/ko/support).

Please translate the page :-)

**Comment by nojiri1098** [comment]
Hello, @jiprastyo. We need your help!
We are in no hurry, but we want you to check it out when you have time 🙏

**Comment by jiprastyo** [comment]
sure, I will try to do it in my spare time.
