### ISSUE TITLE
SNSシェアボタンの実装

### ISSUE THREAD

**Issue by shmokmt** [covid19-oita/covid19#47]
## 改善詳細 / Details of Improvement
- WebサイトがシェアしやすいようにSNSシェアボタンを追加する
- Twitter, Facebook は必須

**Comment by nojiri1098** [comment]
@shmokmt 
わかりやすいように上にしてみた
邪魔かな

PC
![スクリーンショット 2020-03-24 23 38 55](https://user-images.githubusercontent.com/24912801/77438014-a9847980-6e28-11ea-916c-495fb908f3f7.png)

スマホ
![スクリーンショット 2020-03-24 23 39 31](https://user-images.githubusercontent.com/24912801/77438075-bacd8600-6e28-11ea-8a49-38380c10bf31.png)

**Comment by shmokmt** [comment]
@nojiri1098 実装ありがとうございます！良いと思います。Facebookのボタンはその横に数ピクセルあけていい感じに配置できそう。
