### ISSUE TITLE
Image assetの作成

### ISSUE THREAD

**Issue by shmokmt** [covid19-oita/covid19#5]
-  サイト画像の作成
-  各種SNSのOGPの設定

**Comment by nojiri1098** [comment]
@shmokmt 
サイト画像ってロゴとかファビコンのこと？

**Comment by shmokmt** [comment]
・Twitter, Facebook OGP
・README.md のリポジトリ画像
・ファビコン
を変えたいね。

あとは、メニューバーやサイドナビにある
東京都の画像を適宜大分県版に変える必要がありそう。。。

**Comment by nojiri1098** [comment]
作れるところまでやってみる

**Comment by nojiri1098** [comment]
@shmokmt 
ロゴとアイコンとファビコンとREADMEやるから，OGPお願いしたい
