### ISSUE TITLE
デザインカラーの変更

### ISSUE THREAD

**Issue by shmokmt** [covid19-oita/covid19#6]
sassファイルのデザインカラーを大分県版に書き換える

**Comment by nojiri1098** [comment]
@shmokmt 
ちょっと時間があったから適当なロゴを作ってみた
とりあえずこれで公開して，色はあとから考えてもいいんじゃないかな

![スクリーンショット 2020-03-22 17 17 54](https://user-images.githubusercontent.com/24912801/77245336-28c75100-6c61-11ea-9a72-cf7b4c58a9c1.png)

**Comment by shmokmt** [comment]
天才すぎる😭

**Comment by shmokmt** [comment]
GitHub Org のアイコンにもそれ一応設定しとこう🙋‍♂️

**Comment by shmokmt** [comment]
すでに対応済みのためクローズ
