### ISSUE TITLE
感染が疑われるときの対処法をサイトに追加する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#60]
「感染が疑われたときにどうすればいいのかわかるようにしてほしい」という要望がありました

### 詳細
サイドメニューに「感染が疑われるときは」を追加したいです

大分県の該当するページのリンクを貼るだけでもいいそうですが，できればサイト内で完結するような形にしたいです．たとえば，[東京都の問い合わせフロー](https://stopcovid19.metro.tokyo.lg.jp/flow)を改変することもできるかと思います

**Comment by satetsu** [comment]
大分県ウェブページ『[県民のみなさまへ](https://www.pref.oita.jp/uploaded/attachment/2072440.pdf)（PDFファイル）』の内容を東京都版に寄せた表現にするという感じですね。

**Comment by nojiri1098** [comment]
ひとまず「県民のみなさまへ」を「感染が疑われるときは」としてサイドバーに追加しておこうと思います

**Comment by nojiri1098** [comment]
#140 に引き継ぎ
