### ISSUE TITLE
大分県との連携

### ISSUE THREAD

**Issue by satetsu** [covid19-oita/covid19#61]
Code for Oitaとして、大分県と連携したサイト運営ができるように情報政策課と協議をしています。

こちらから投げかけ予定の話題。

- 大分県側にこのサイトの存在を報告
- 大分県ウェブページに公開するデータをオープンデータ（CSV形式）にする（ #8 に関連）

他にも要望、協議事項がありましたら挙げてください。

**Comment by varu3** [comment]
現状、圧倒的に公開データが少ないことが問題かと思われます。
具体的には、

- 陽性患者の属性の退院可否
- 検査実施状況
- 検査陽性者の状況
- 検査実施人数
- 検査実施件数
- 新型コロナコールセンター相談件数
- 新型コロナ受診相談窓口相談件数

等のダッシュボードを作成するための情報が足りていません。

これらの情報を東京都に準ずるフォーマットで公開していただければ、ダッシュボードの作成など容易になるかと思われますので是非とも進言いただきたいです。

**Comment by satetsu** [comment]
3月26日に『[オープンデータ利活用促進セミナー＆アイデアソン](http://www.hyper.or.jp/activity/opendata2020)』がazitoで開催されます。主催は大分県、ハイパーネットワーク社会研究所。

このなかで大分県新型コロナウイルス感染症対策サイトの話題を出します。
参加できる人がいればご参加ください。オンライン参加も可です。方法は明日お知らせします。

**Comment by shmokmt** [comment]
自分も @varusan  さんと同じで情報の少なさに不満を感じております。
公開されている情報が少ないがためにダッシュボードもかなり簡素なものに必然的になってしまっている状態です。
本来は　https://twitter.com/mattn_jp/status/1242656273373388800?s=20
のツイートのように完治した人を差し引いたアクティブな陽性患者数を知りたいニーズがあると思っております。

**Comment by satetsu** [comment]
『[オープンデータ利活用促進セミナー＆アイデアソン](http://www.hyper.or.jp/activity/opendata2020)』ただいま開催中です。オンライン参加は申し込みをした人のみでした。

ここでコメントいただいた話題は議論のネタとして出しますね。

**Comment by satetsu** [comment]
県情報政策課とこのIssueを共有しました。現在協議してもらっているところです。

### 現在公開されていないデータのフォーマット
下記2つのデータについてはCSV形式のフォーマットがあります。

- 440001_oita_covid19_inspections.csv
- 440001_oita_covid19_patients.csv

下記に対応する東京都のフォーマット、お手すきの際にピックアップしていただけますか？（これは佐藤も時間を見つけて対応します）

> * 陽性患者の属性の退院可否
> * 検査実施状況
> * 検査陽性者の状況
> * 検査実施人数
> * 検査実施件数
> * 新型コロナコールセンター相談件数
> * 新型コロナ受診相談窓口相談件数

**Comment by varu3** [comment]
> 下記に対応する東京都のフォーマット

本家リポジトリの/static/data配下に置かれています
（ダッシュボードはこのCSVを元に集計したデータを/data/data.jsonに置いて、画面を描画している）
https://github.com/tokyo-metropolitan-gov/covid19/tree/development/static/data

**Comment by varu3** [comment]
こちらも参考になります

COVID-19Hokkaidoデータ編①スクレイピングなどによる初期データ作成
https://qiita.com/Kanahiro/items/b47984fbf77f4e632663#%E6%9D%B1%E4%BA%AC%E9%83%BD%E5%85%AC%E5%BC%8F%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AE%E3%83%87%E3%83%BC%E3%82%BF

**Comment by satetsu** [comment]
大分県情報政策課と協議継続中です。
データ形式について確認が終わればオープンデータとして『[大分県オープンデータカタログサイト](https://odcs.bodik.jp/440001/)』に掲載される予定です。

- [大分県オープンデータカタログサイト](https://odcs.bodik.jp/440001/)

### [440001_oita_covid19_patients.csv](https://github.com/covid19-oita/covid19/blob/development/static/data/440001_oita_covid19_patients.csv)
- フォーマットに合わせてデータの作りこみをする
- ただし「だれが退院したか」情報は公開しないので［退院済フラグ］はブランクのままとする

### [440001_oita_covid19_inspections.csv](https://github.com/covid19-oita/covid19/blob/development/static/data/440001_oita_covid19_inspections.csv)
- （確認中）項目を拡張してデータの作りこみをする
    - 現在の項目［日付,検査人数］
    - 拡張の項目［日付,検査実施件数,うち陽性,相談窓口相談件数,退院人数］
- 日毎の退院人数はこのデータから積み上げる

上記の対応で #111 を実現できないでしょうか。

**Comment by nojiri1098** [comment]
@satetsu 
ありがとうございます！#111 対応可能です

patients.csv について

- 退院フラグを使わないのであれば，誤解を生むので消してほしいです

inspections.csv について

- inspections は「検査」という意味なので，退院人数を含めるなら別の名前にしたいです
- 死亡人数の項目は追加できますか (出ないことを祈りますが)
- 相談窓口相談件数は種別が違うので，別ファイルにしたいです ([イメージ (右3カラムで十分です)](https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000070/resource/38f343c9-d70c-495f-8cd1-1f401f75a0af))

**Comment by satetsu** [comment]
> patients.csv について
> 
> * 退院フラグを使わないのであれば，誤解を生むので消してほしいです

ブランクのままで行きたいに+1。
理由はほかにも未使用でブランクの項目があるからです。

> inspections.csv について

> * 死亡人数の項目は追加できますか (出ないことを祈りますが)

追加を提案しましょう。

> * 相談窓口相談件数は種別が違うので，別ファイルにしたいです ([イメージ (右3カラムで十分です)](https://catalog.data.metro.tokyo.lg.jp/dataset/t000010d0000000070/resource/38f343c9-d70c-495f-8cd1-1f401f75a0af))

システム的には賛成。ただ、データを作る側の手間を考えると1ファイルの編集のみで作業が終わるのであれば先方の負担を軽減したいです。

> * inspections は「検査」という意味なので，退院人数を含めるなら別の名前にしたいです

上記のコメントを踏まえて、良いファイル名を提案いただけると助かります。

**Comment by nojiri1098** [comment]
@satetsu 
退院フラグについてはブランクのままで大丈夫です

相談窓口相談件数についても承知しました

ファイル名については開発チームで話し合ってからご報告します

**Comment by nojiri1098** [comment]
@satetsu 
ファイル名を検討した結果，`440001_oita_covid19_data_summary.csv` になりました
よろしくお願いします

**Comment by satetsu** [comment]
『[大分県オープンデータカタログサイト](https://odcs.bodik.jp/440001/)』に掲載されました。
ご確認ください！

[https://data.bodik.jp/dataset/_covid19](https://data.bodik.jp/dataset/_covid19)

**Comment by satetsu** [comment]
ファイル名のアンダーバーが消えてしまう問題点を確認しました。県に確認中です。

**Comment by satetsu** [comment]
文字コードがシフトJISになっていることを確認しました。UTF-8でアップロードしてもらえるように県に伝えました。

**Comment by satetsu** [comment]
> ファイル名のアンダーバーが消えてしまう問題点を確認しました。県に確認中です。

ファイル名のアンダーバーが消えてしまうのはカタログサイトの仕様だと判明しました。
お手数ですが、アンダーバーを除いた下記のファイル名で処理を行ってください。

- 440001oitacovid19patients.csv
- 440001oitacovid19datasummary.csv

**Comment by satetsu** [comment]
> 文字コードがシフトJISになっていることを確認しました。UTF-8でアップロードしてもらえるように県に伝えました。

文字コードをUTF-8で統一していただきました。

**Comment by satetsu** [comment]
今後は記者発表後[大分県オープンデータカタログサイト](https://odcs.bodik.jp/440001/)『[新型コロナウイルス関連 - データセット - CKAN](https://data.bodik.jp/dataset/_covid19)』にデータが反映されます。ただ、タイムラグがある点はご承知おきください。

**Comment by shmokmt** [comment]
@nojiri1098 
このissueのスコープをどこまでにしましょうか。
一旦ここでクローズしますか？ 🤔

**Comment by nojiri1098** [comment]
@shmokmt 
連携できたので，これは閉じましょう

**Comment by nojiri1098** [comment]
@satetsu 
続きはSlackでやりとりしたいのですが，参加していただけますか
https://join.slack.com/t/covid19-oita/shared_invite/zt-d211rqiv-SBc88NBVTe8Jpo_CcloKRw
