### ISSUE TITLE
「最新のお知らせ」の追加

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#62]
コロナに関するニュースなどを表示したいです

実装方法は東京都に倣います

完成イメージ (画像は東京都のものです)
![スクリーンショット 2020-03-25 9 47 31](https://user-images.githubusercontent.com/24912801/77490226-acf62000-6e7d-11ea-9596-77805167811e.png)

**Comment by satetsu** [comment]
東京都の場合は東京都ページへの内部リンクでした。

大分県版では外部リンクが中心になる感じでしょうか。下記に例示します。

- [新型コロナ医療センター検査終わり２人陽性(2020/03/25(水))](http://www.e-obs.com/news/detail.php?id=03250048427&day=20200325) - OBS大分放送ニュース
- [新たに大分医療センター看護師２人の感染確認](https://www.oita-press.co.jp/1010000000/2020/03/25/JIT202003251203) - 大分合同新聞
- [玖珠町の童話祭中止　新型コロナ感染予防で](https://www.oita-press.co.jp/1010000000/2020/03/25/133351058) - 大分合同新聞

注意点としては、どこまでの話題を拾うかのジャッジが難しい点です。例えば下記の新型コロナウイルスの影響で開催が延期になった東京オリンピックに対する大分県内の話題。これは本サイトでお知らせすることがふさわしいか否か...などです。

- [東京五輪パラ延期　県内アスリートの反応](https://www.tostv.jp/news/5931.html) - TOSニュース

**Comment by satetsu** [comment]
#156 に関連。

最新情報のフィードが下記URLから取得できます。この項目を「最新のお知らせ」として表示したいです。

http://www.pref.oita.jp/rss/10/site-1000786.xml
