### ISSUE TITLE
大分市及び報道機関へのリンクをはる

### ISSUE THREAD

**Issue by yukifujino** [covid19-oita/covid19#64]
大分県の公式サイトの更新がやや遅いので、現状感染者がでている大分市へもリンクをはる。
報道機関によってはコロナ関連の専用サイトをつくっています、更新もはやいので、そこへもリンクを貼っておくのが適当ではないかと思われます。

・大分市公式「新型コロナウイルスに関連する情報」
https://www.city.oita.oita.jp/o029/coronavirus.html

・大分合同新聞>注目まとめ>新型肺炎
https://www.oita-press.co.jp/followup/Covid19

・NHK大分　 大分 NEWS WEB
https://www3.nhk.or.jp/lnews/oita/

**Comment by shmokmt** [comment]
@yukifujino 
issue報告ありがとうございます！自分も賛成です。
自分も大分県の公式サイトは更新が遅いと感じていたところでした。
