### ISSUE TITLE
コミッターの募集

### ISSUE THREAD

**Issue by shmokmt** [covid19-oita/covid19#68]
現在は @shmokmt と @nojiri1098 の2人でissueの整理やPRのレビュー、デプロイを行っておりますが、4月以降は2人だけでメンテナンスすることが難しい状況です。

そこで covid19-oita では、issueの整理、PRのレビューおよびデプロイを継続的に行ってくださるコミッターを募集しています。

コミッターとして協力してくださる方は、このissueにコメントをお願いいたします。

**Comment by shmokmt** [comment]
@satetsu 佐藤さんをコミッターとしてこのGitHub Org に追加しても良いでしょうか？
今後の開発がスムーズに行えるようになると思います。

**Comment by satetsu** [comment]
コミッターとして協力します！

**Comment by nojiri1098** [comment]
@satetsu 
ありがとうございます！
招待しましたので，https://github.com/covid19-oita にアクセスして参加してください

**Comment by satetsu** [comment]
Joinしました。

**Comment by nojiri1098** [comment]
@varusan
招待しましたので，https://github.com/covid19-oita にアクセスして参加してください

**Comment by varu3** [comment]
参加しました。よろしくお願いいたします。
