### ISSUE TITLE
サイトのコンセプトを再確認

### ISSUE THREAD

**Issue by satetsu** [covid19-oita/covid19#86]
『大分県 新型コロナウイルス感染症対策サイト (非公式)』のコンセプトを再確認したうえで、どんなコンテンツを提供できるかの認識合わせをしたいです。

『[当サイトについて](https://oita.stopcovid19.jp/about)』では次のように記載されています。

> 当サイトは大分県内における新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、 有志 が開設したものです。
> 
> 複製・改変が許されたオープンソースライセンスで公開されている、 東京都 新型コロナウイルス対策サイト のしくみを利用しています。
> 
> 大分県による公式情報と客観的な数値をわかりやすく伝えることにより、大分県にお住まいの方や、大分県内に拠点を持つ企業の方、大分県を訪れる方が、現状を把握して適切な対策を取れるようにすることを目的としています。

#61 大分県との連携にも関連する話題です。『[オープンデータ利活用促進セミナー＆アイデアソン](http://www.hyper.or.jp/activity/opendata2020)』で得られたフィードバックなのですが、今後陽性患者の推移が小康状態を保った場合、このサイトを見る人が減ることが想定されます（[佐賀県](https://stopcovid19.code4saga.org/)はまさに小康状態です）。この状態は喜ばしいのですが、日々見てもらえるコンテンツを提供することも必要だと考えます。

例えば[「#大分コロナSOS」飲食店や過剰在庫を抱えた個人・企業さまへ](https://oitasos.com/)で集められている情報は県民にとって有益な情報です。これを何らかの形でダッシュボード化するのもありでしょう。

ここで考えたいのは2点です。

- 大分県提供のデータ以外のデータを基にしたダッシュボードもあってよいのではないか
- 上記がアリだと仮定すると、「感染症対策」のサイトからは若干離れてくる（しかし県民には有益な）のでサイトを再定義するとすれば何か

ご意見いただきたいです。

**Comment by shmokmt** [comment]
フィードバック報告ありがとうございます！
上記の2点を建設的に議論するためには、行動規範が必要だと思います。
行動規約を設定すると必然的にissueの優先度をラベル付け（またはそのissueを取り組まない）などが決められるはずです。
[東京都公式サイトをforkした時には行動規約はあった](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/CODE_OF_CONDUCT.md)のですが、当初の関係者は2人だけだったのであとから必要に応じて追加すれば良いと判断し、行動規約を削除してしまっていました。最初は最小限の機能で素早くリリースすることだけを意識していたからです。例えば、東京都の場合だと**都民の生命と健康を守る**というミッションを公開しているため、それに反する情報は極力省かれているようになっていると思います。

私はこのサイトに関しては「感染症対策」サイトとして運用していきたいと考えています。
一つのサイトに様々な情報を詰め込むとかえってそれが何を伝えたいのかわからなくなってしまい、現在のサイトの魅力を大きく損ねてしまうことを懸念しております。
後方互換性およびサイトの方向性は壊さない/ずらさないようにしていきたいと思っていますが、いかがでしょうか。 🤔

**Comment by varu3** [comment]
> 上記の2点を建設的に議論するためには、行動規範が必要だと思います。

私は東京都のCoCに共感してこのサービスにContributeしたいと思いましたので、
CoCは東京都のものを踏襲する形が良いかと思います。

> 私はこのサイトに関しては「感染症対策」サイトとして運用していきたいと考えています。

:+1:

**Comment by nojiri1098** [comment]
@shmokmt @varusanさんに賛成します

日々見られるコンテンツにすることは魅了的ではありますが，このサイトの役割は，あくまでも感染症に関する情報をわかりやすく提供することだと思います

**Comment by shmokmt** [comment]
@satetsu 問題ないようでしたら、東京都公式サイトと同じCode of Conductを追加し、こちらのissueをクローズしたいと考えております。

**Comment by satetsu** [comment]
返事遅れて申し訳ないです。
開発チームでの意思統一が図れているので、異論はありません。
クローズしましょう。
