### ISSUE TITLE
GitHub Action実行時にtool/convert/convert_csv_to_json.pyの結果がページへ反映されていない

### ISSUE THREAD

**Issue by varu3** [covid19-oita/covid19#89]
## 起こっている問題 / The Problem
- https://github.com/covid19-oita/covid19/issues/81 で追加したが更新がdevelopmentのページに反映されていない

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by varu3** [comment]
![スクリーンショット 2020-03-28 12 38 07](https://user-images.githubusercontent.com/35091584/77814058-0023d900-70f1-11ea-8bc7-1bbb9fde066d.png)

GitHub Actionsの`deploy`実行時にgit pullしてきているため?

**Comment by nojiri1098** [comment]
@varusan 
GitHub Actions で `data.json` をコミットする感じですかね
東京都はボットでしたが，`data.json` をコミットしていました

**Comment by varu3** [comment]
はい、そのように実装しようかと思います。
