### ISSUE TITLE
表示用 json を整理する

### ISSUE THREAD

**Issue by nojiri1098** [covid19-oita/covid19#94]
#92 で議論にあがった

今はなんでも `data.json` にデータを詰め込んでいます

```
data.json
- patients
- patients_summary
- inspections_summary
```

しかし，#92 で `age` という項目が増えたことをきっかけに，今後データが増えることを考えると，より具体的な名前で管理したいと思いました

たとえば，以下のように

```
patients.json
- attributes
- summary
- age

inspections.json
- summary
```

分け方は例です，より適切なものがあれば教えてください

**Comment by varu3** [comment]
data.jsonはスクリプトでCSVファイルから生成するようにしたので、
すでに人が直接管理するものではありません。
従来通り、data.jsonにまとめる方針が良いかと思います。

ただ今後もデータが増えていくとなると、
人の入力が必要なCSVファイルに関しては複数の入力ファイルに分けるなど必要かと思います。
その場合、データの整形スクリプト側でjsonを管理することになりますが。

**Comment by nojiri1098** [comment]
@varusan 
確かにそうですね…では json はこのまま運用することにします

**Comment by varu3** [comment]
この件、再考してみたんですが例えば1つのダッシュボードにつき1つのcsv,1つの jsonとするのはどうでしょうか。

例えば、
patients_summary.csv -> patients_summary.json を作成するようにして、
陽性患者数のダッシュボードにはそのpatients_summary.json を読むようにする、という感じです。

こうすれば、
スクリプトもcsv -> json化するというデータが増えるごとに改修しなくても良くなるかと。

**Comment by varu3** [comment]
それだとscript内で集計する処理が
ある場合にまた一手間加えることになりますね…

**Comment by nojiri1098** [comment]
@varusan さんの「json はすでに人が直接管理するものではない」という観点から，データがよっぽど大きくならない限り `data.json` に集約していいと思います
